Merge ade20k branch
alvinsunyixiao/disinfect-perception pull request #1
Opened 2020-06-03 00:31 UTC by RogerQi

Main changes

- Implement a generic base data set for further development; migrated COCO dataset to use baseset.
- Implemented and tested the 150 classes ADE20K dataset.
- Added load pre-trained weights logic to better support fine-tuning.

2020-06-03 01:24 UTC, alvinsunyixiao requested changes
The whole `pretrained` thing, I am more inclined to fall back to the original implementation. This new implementation is limited to backbone weight loading, but not the whole model, which really violates the intention of creating this option. We should implement better `pretrain` loading logics in the future. But for now, I don't think fine tuning will be beneficial, and / or this `pretrain` option will add any convenience to the training process.

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/data.py
> +        self.img_dir = "NA"
If this is `N/A` then we should remove it from the base

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/data.py
> +    DEFAULT_PARAMS = DEFAULT_PARAMS(
```suggestion
    DEFAULT_PARAMS = BaseSet.DEFAULT_PARAMS(
```

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/data.py
> +        img_id = self.img_ids[ind]
`key` is more generic then `index`. considering building mixed Dataset in the future, we should leave the name as `key`.

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/data.py
> +        assert len(self.img_path_list) == len(self.scenario_list) == len(self.seg_path_list)
Assertion failure message?

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/model.py
> +                self.load_state_dict(pretrained_cp)
Do we get other reliable pre-train weights other than the pytorch official sources?

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/model.py
> +
I don't see why this is necessary as the urls can be imported directly.

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/train.py
> +import argparse
alphabetical order

2020-06-03 01:24 UTC, alvinsunyixiao commented on segmentation/train.py
> +    train_set = DataLoader(train_set, batch_size=p.data.batch_size, shuffle=True,
put the coco stuff back as comments for future references.

2020-06-04 04:01 UTC, RogerQi commented on segmentation/model.py
> +
My idea would be to leave the URLs here for future references since we are isolating the functionality of training with pretrained weight. In this case, exposing these URLs to users would be more convenient than having users finding pretrained weights themselves.

2020-06-04 04:15 UTC, alvinsunyixiao commented on segmentation/model.py
> +
I don't think we will have any user other than the 2 of us 😂

2020-06-04 04:19 UTC, alvinsunyixiao commented on segmentation/model.py
> +
And since these urls are for loading pretrained `backbone`, which I don't think we can pretrian anything better than `torchvision` weights, I think a URL to the `torchvision` implementation should suffice for the purpose of referencing.

2020-06-04 04:54 UTC, RogerQi commented on segmentation/model.py
> +                self.load_state_dict(pretrained_cp)
We do. For example, training on COCO and ADE20K and then using the trained weights as pretrained weight to carry out high touch surface segmentation might be an option.

2020-06-04 04:55 UTC, RogerQi commented on segmentation/model.py
> +
We may need pretrained weights other than ImageNet pretrained one. See explanation above

2020-06-04 04:56 UTC, RogerQi commented
All issues are addressed in the most recent two commits and under comments.

2020-06-04 05:05 UTC, alvinsunyixiao requested changes
Still thinks pretrained logic is too complicated.

2020-06-05 05:18 UTC, alvinsunyixiao approved these changes
To prevent from explicitly requiring `pretrained` option to load imagenet weights, I reverted the imagenet loading logic on the model class just to have imagenet weights loaded no matter what.

2020-06-05 05:18 UTC, merged